### ISSUE TITLE
Gather network information

### ISSUE THREAD

**Issue by dmmcquay** [dmmcquay/sqrl#1]
Gather the following information and return in human readable format:
- interface Name
- IP Address
- MAC address
- Speed (1gb/10gb/100gb)
- Link (up/down)

**Comment by cmoussa1** [comment]
I'll do this one! #TeamSqrl

**Comment by cmoussa1** [comment]
I am wondering what Link is? Is it related to the Flags field in the gopsutil interface InterfaceStat? Flags returns things likes "up", "broadcast", and "multicast" when I call it on my terminal.

**Comment by dmmcquay** [comment]
I think what Thomas wanted here was if the link is up or down.  I do believe it would be in the Flags part of InterfaceStat... Let me do some further investigation and ask Thomas as well.

**Comment by cmoussa1** [comment]
I have been trying to find go packages that are capable of determining a network speed. So far, all I have found are Linux terminal commands that display different network speed attributes. Do you have any advice/suggestions as to what I should do?

**Comment by dmmcquay** [comment]
Don't worry about it for now.  I'll investigate a bit more and let you know.  Continue forward on the other things.
