### ISSUE TITLE
Log information to syslog

### ISSUE THREAD

**Issue by dmmcquay** [dmmcquay/sqrl#10]
Investigate and write code to log the structs to syslog so that our information can be scrapped by splunk.

**Comment by cmoussa1** [comment]
I can do this one

**Comment by cmoussa1** [comment]
Should I be logging the different information functions (GetCPUInfo, GetInterfaces, etc.) within main.go? Or should each separate program log its information within their respective programs?

**Comment by dmmcquay** [comment]
Basically just learn how to do it and wait for the report struct to be done cause that is what we will be logging.  Does that make sense?

**Comment by cmoussa1** [comment]
Got it, thanks.

**Comment by dmmcquay** [comment]
In the mean time... you can always tackle the HDD issue... :)

**Comment by dmmcquay** [comment]
just check out master again and create a new branch and work on it.. if you want to, obviously
