### ISSUE TITLE
Gather cpu information

### ISSUE THREAD

**Issue by dmmcquay** [dmmcquay/sqrl#2]
Gather the following information and return in human readable format:
- Number of CPUs (Sockets)
- Number of Cores per CPU
- Number of Threads per Core
- Model of CPU
- Speed of CPU
- Serial Number
- Other pertinent/interesting information.

**Comment by dlarson3** [comment]
I'll do this one.

**Comment by dlarson3** [comment]
I'm having issues finding the Number of Threads per Core. It's not in the gopsutil and I was having issues finding it anywhere else.

**Comment by dmmcquay** [comment]
Don't worry about it.  I don't think we will even need it. Just gather the other information. :)

**Comment by dlarson3** [comment]
I was having issues committing my changes. I did the same steps Chris and Delaney did and for some reason mine doesn't work.
