### ISSUE TITLE
create webserver with API

### ISSUE THREAD

**Issue by dmmcquay** [dmmcquay/sqrl#22]
Create a webserver with an API that would allow us to run the different commands hitting a specific route.

For example:

``` bash
curl localhost:8080/api/v0/cpu
```

would cause sqrl to log the cpu info

**Comment by cmoussa1** [comment]
I will do this one. I am pretty sure you showed me an example of this one, but I forgot the process. Is there a chance we can meet and go over this in depth? Or do you have any suggestions as to where I should go to read about how to do this? I have been searching on the internet and most of what I am getting are tutorials on how to install Apache on my terminal.

**Comment by dmmcquay** [comment]
https://golang.org/doc/articles/wiki/ 

Try to read and work through as much of that as possible.  I'll come swing by after lunch.
