### ISSUE TITLE
Gather HDD information

### ISSUE THREAD

**Issue by dmmcquay** [dmmcquay/sqrl#3]
Gather the following information and return in human readable format:
- How many HDDs are Present
- What partitions are on the system
- Free space one each HDD or partition
- HDD type (SSD vs. HDD)
- Serial Numbers/Model Numbers
- As much information about the drives as possible.

**Comment by dmmcquay** [comment]
I'll do this

**Comment by dlarson3** [comment]
I'll do this one.
